import { Game } from '../../../../shared/models/game';
import { User } from '../../../../shared/models/user';
import { Achievement, AchievementTier } from '../../../../shared/models/achievement';

export const MOCK_GAMES: Game[] = [
    {
        id: 1,
        title: 'Alpha Quest',
        description: 'An epic RPG adventure.',
        genre: 'RPG',
        tags: ['rpg', 'adventure'],
        platform: ['PC', 'PS5'],
        developer: 'Dev Studio A',
        publisher: 'Publisher A',
        releaseDate: '2023-01-01',
        imageName: 'alpha.png',
        popularityScore: 9.5,
        isTracked: false,
        isFavorite: false,
        achievementCount: 12,
    },
    {
        id: 2,
        title: 'Beta Strike',
        description: 'Fast-paced action game.',
        genre: 'Action',
        tags: ['action', 'multiplayer'],
        platform: ['PC', 'Xbox'],
        developer: 'Dev Studio B',
        publisher: 'Publisher B',
        releaseDate: '2023-05-01',
        imageName: 'beta.png',
        popularityScore: 8.2,
        isTracked: true,
        isFavorite: true,
        achievementCount: 8,
    },
    {
        id: 3,
        title: 'Gamma Puzzle',
        description: 'Challenging puzzle game.',
        genre: 'Puzzle',
        tags: ['puzzle', 'singleplayer'],
        platform: ['Switch', 'PC'],
        developer: 'Dev Studio C',
        publisher: 'Publisher C',
        releaseDate: '2022-11-15',
        imageName: 'gamma.png',
        isTracked: false,
        isFavorite: false,
        achievementCount: 5,
    },
    {
        id: 4,
        title: 'Delta Racing',
        description: 'High-speed racing fun.',
        genre: 'Racing',
        tags: ['racing', 'multiplayer'],
        platform: ['PC', 'PS5'],
        developer: 'Dev Studio D',
        publisher: 'Publisher D',
        releaseDate: '2023-02-20',
        imageName: 'delta.png',
        popularityScore: 9.8,
        isTracked: true,
        isFavorite: true,
        achievementCount: 10,
    },
];

export const MOCK_POPULAR_GAMES: Game[] = [
    {
        id: 4,
        title: 'Delta Racing',
        description: 'High-speed racing fun.',
        genre: 'Racing',
        tags: ['racing', 'multiplayer'],
        platform: ['PC', 'PS5'],
        developer: 'Dev Studio D',
        publisher: 'Publisher D',
        releaseDate: '2023-02-20',
        imageName: 'delta.png',
        popularityScore: 9.8,
        isTracked: true,
        isFavorite: true,
        achievementCount: 10,
    },
];

export const MOCK_GAME: Game = {
    id: 1,
    title: 'Alpha Quest',
    description: 'An epic RPG adventure.',
    genre: 'RPG',
    tags: ['rpg', 'adventure'],
    platform: ['PC', 'PS5'],
    developer: 'Dev Studio A',
    publisher: 'Publisher A',
    releaseDate: '2023-01-01',
    imageName: 'alpha.png',
    popularityScore: 9.5,
    isTracked: false,
    isFavorite: false,
    achievementCount: 12,
};

export const MOCK_USER: User = { id: 1, name: 'Mock User', email: 'mock@test.de' };

export const MOCK_ACHIEVEMENTS: Achievement[] = [
    {
        id: 101,
        gameId: 1,
        title: 'Erste Schritte',
        description: 'Schließe das Tutorial ab.',
        difficulty: AchievementTier.Bronze,
        isCompleted: true,
    },
    {
        id: 102,
        gameId: 1,
        title: 'Meister-Entdecker',
        description: 'Finde alle versteckten Truhen im ersten Level.',
        difficulty: AchievementTier.Silver,
        isCompleted: false,
    },
    {
        id: 103,
        gameId: 1,
        title: 'Unbesiegbar',
        description: 'Besiege einen Boss ohne Schaden zu nehmen.',
        difficulty: AchievementTier.Gold,
        isCompleted: false,
    },
    {
        id: 104,
        gameId: 1,
        title: 'Gottgleicher Status',
        description: 'Schalte alle anderen Achievements frei.',
        difficulty: AchievementTier.Platinum,
        isCompleted: false,
    },
];
